name: Hello World

on:
  workflow_dispatch:
    inputs:
      name:
        default: test
        type: string
      age:
        options: 
          - male
          - female
        type: choice
      Married:
        type: boolean   


jobs:
  demo:
    runs-on: ubuntu-latest
    steps:
      - name: Greetings
        run: echo "${{ inputs.name }}"
